### ISSUE TITLE
Difference in JSON RPC response eth_sendRawTransaction #1 goerli chain

### ISSUE THREAD

**Issue by matilote** [NethermindEth/nethermind#1010]
Request: {"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf8c8820d6c808306a5d1947301cfa0e1756b71869e93d4e4dca5c7d0eb0aa680b864995b2cff000000000000000000000000bac3fea4f8bd2bc76de1fa0f0ce6210865c8ba3d0000000000000000000000000000000000000000000000000de0b6b3a7640000a5c2ae212a7246d2019e19ef3b8772821ee3f7f8a50d6e4d5c93c25ed0ea725281eba03f457c3ef9202dc3d0320c1edfdaccfb16084f6296ef4cb56a6fda2b66ecbd28a07cc1a51a0c122e5ca10ca9839e578406843e5b7c19e980097486b2653d876009"],"id":33} 

Response Nethermind: {"id":33,"jsonrpc":"2.0","result":"0x5cc146f1d5575aa9ef2c97ea65678c03d1ac2688d7513f0372f181cde920d621"} 

Response Parity: {"jsonrpc":"2.0","error":{"code":-32010,"message":"Transaction with the same hash was already imported."},"id":33}

**Comment by epheph** [comment]
Why was this closed? I just ran into this issue and it surprised me. It seems like the correct thing to do here is notify the client that the transaction they are trying to submit is not valid, instead of simply hashing it and returning it, "Transaction with the same hash was already imported", or even just "nonce too low" (if you don't have a full list of transactionHashes)

**Comment by MicahZoltu** [comment]
I personally prefer Nethermind's behavior for hash already exists, that feels like it should be an idempotent call.  Nonce too low is a bit more questionable though, especially if Nethermind drops the transaction from its pending queue.
