### ISSUE TITLE
Licensing / readme of Cortex repos

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1057]
it may be important to either remove the donations link or clearly state that the donations are not for the Nethermind project while we are merging the libs

---

I think for now there is no rush with it but later we may consider things like:
* making cortex repos private
* using cortex repos as reusable libs for other project (may have no time / resources for it as it would require some maintenance)
* using Cortex libs as NuGets for Nethermind (probably harder than maintaining monorepo)
* other things?

---

**Comment by sgryphon** [comment]
re donations. Same thinking, while I was updating the copyright statements, I also removed the donation details, so already gone.

**Comment by sgryphon** [comment]
re library structure. Yes, can move into one repo, and then archive out the other ones.

You can have multiple nuget packages published from one repo; I have this in my Essential.Diagnostics project, that has a half dozen+ nuget packages.

You should also be able to set up local build references (pre-publish) with nuget config and local folder based package sources. Then just have build script build them in the correct order. 

There are benefits both ways, e.g. keeping separate allows them to evolve and version separately, but either way is fine; as I said, I have other projects with one repo.

(Actually, one of the reasons I pulled them out into separate repos originally was because of Nethermind, to make it possible to share components, in case that was the way we collaborated).

**Comment by tkstanczak** [comment]
I like the idea of mono repo with nugets for the outside world
