### ISSUE TITLE
BeaconNodeVersion - compare with Nethermind.Core.ClientVersion

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1066]
Can we reuse the same version as the 1.0 client?
Are there any improvements possible (as long as they follow the same format as eth1)
see versions here: https://ethstats.net/

Client Name/version-commit/operating system/.net version
Nethermind/v1.2.0-421312f2/X64-Linux 4.15.0-47-generic/Core3.0.0

**Comment by sgryphon** [comment]
The API specification (swagger) for /node/version specifies the HTTP User-Agent format, https://tools.ietf.org/html/rfc7231#section-5.5.3

This consists of product identifiers (one or more) of the token + version + comments (for platform, etc)

So "Nethermind/1.2.0+421312f2 (X64-Linux 4.15.0-47-generic/Core3.0.0)" or could be "Nethermind/v1.2.. (X64-Linux 4.15.0-47-generic)(Core3.0.0)"

The current code uses the environment name as a comment (Production, i.e. mainnet, vs Development, i.e. minimal).

I will change the name to Nethermind and add (operating_system/dotnet_version) as a comment.

**Comment by sgryphon** [comment]
For version numbers, I recommend you follow the Semantic Versioning specification, https://semver.org/

I usually use GitVersion to generate the SemVer numbers, https://github.com/GitTools/GitVersion.

So "Nethermind/1.3.0-beta.3" is a lower version than "Nethermind/1.3.0". The "-" is for pre-release identifiers, and "+" for build information (and there is no "v").

Build metadata can be anything, e.g. SHA is common "Nethermind/1.3.0+421312f2". Originally I had just the commit SHA, but recently I changed it to also include commits since base: "0.3.0+180.Sha.c848961"; easy enough to change back.

Note that the version comes from the DLL, inserted during the build, so no code change. But looking at your build scripts, I think the publishing is in build-runner.sh and doesn't specify the version, or seem to update values (such as the old AssemblyInfo.cs), but I could be wrong. In Runner.csproj there is a before build target that seems to manually grab the git hash. So maybe it doesn't insert that.

GitVersion will automatically generate the version according to the branch, e.g. for pre-release, etc, depending on the scheme used.

See the build.ps1 in the master of my old repo for how to use and grab the output of GitVersion and use it to set the values during dotnet publish.

I will talk to Mateusz about maybe including it in the build scripts.
