### ISSUE TITLE
Add license info to each file

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1067]
Nothing super critical - just need to launch an automatic tool that will add the same licensing info everywhere.

Whichever of us finds time for it first. No rush.

**Comment by sgryphon** [comment]
Just questioning if you really need to do this. I know that the GPL pages recommend it, with the main reason being if someone copies out just a file or class by itself, then it is clear what the licence is, but personally, I don't think it has a lot of value.

**Comment by sgryphon** [comment]
Probably more important is to actually include the full licence text in the repository, a common mistake. The LGPL file is actually *additional terms* to the GPL licence. The full text of the licence is actually both full files. 

The GPL page instructions are to put one file called COPYING with the GPL, and then a second file called COPYING-LESSER with the additional LGPL terms. https://www.gnu.org/licenses/gpl-howto.html

Just putting the files there isn't enough though, you actually need to have some text that explicitly says the licence is being used (i.e. the files aren't just there for information). I have just stuck that text in the main readme, rather than each file, but either works. Having a little icon may also work.

For the licence files, I actually stick the text of both documents (LGPL addititional terms, plus the main GPL) into a single LICENCE.txt file.

However this file is often not automatically recognised, as some tools just (incorrectly) think that the LGPL additional terms are the full licence, and generate that as the stub (e.g. I think this happens on github if you create a project -- it only gives you the additional terms file).

**Comment by LukaszRozmej** [comment]
We just need to run code cleanup from R# https://blog.jetbrains.com/dotnet/2010/12/20/automating-file-header-information-with-resharper/

**Comment by LukaszRozmej** [comment]
Couldn't make it work from Rider, even as this was an option. But worked like a charm from resharper. Side effect was that old style comments with /* were unified to // comments.
