### ISSUE TITLE
After merging is finished probably want to rename Core2 back to BeaconNode

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#1068]

**Comment by sgryphon** [comment]
First of all, BeaconNode is *not* the same as core, so this would be a bad idea.

The Eth2 spec is modularised, with the two main components BeaconNode and HonestValidator, with an API for the two to communicate. The intention is that, long term, you can mix and match nodes and validators from different projects (because they use the same API).

So, there should be no direct dependency from one to the other (either way). Both depend on the API specification (i.e. one side could be .NET and one side could be Java).

For implementation, both the .NET components can probably share the actual API code, and there will be some common functionality required, e.g. crypto and data structures. Hence why I had started with containers separate, crypto separate, etc. But I haven't written the validator yet, so don't know the final form.

Current plan is to add some tests around the QuickStart and debug why it is crashing, then move on to honest validator + API, as both are needed for a running implementation. (Quick Start is enough to get things working, then come back to deposit contract later for the actual integration with Eth1)

----

So, Containers are meant to be plain data classes, so I have avoided having them depend on other things. The way to break up dependencies to to have abstractions, and then have the implementations depend on them (from both sides). 

With a hexagonal architecture, dependency on the centre is okay, e.g. Storage => BeaconNode (e.g. IStore), but if I wanted further decoupling I would have something like Storage.Abstractions that they both depend on. (This would require abstracting some of the services storage uses like getting parameters, utility functions, etc).

Core2 is probably close to Containers, and you could merge/rename Containers and Core2 at some point... but remove dependencies first.
