### ISSUE TITLE
eth_getStorageAt wire encoding

### ISSUE THREAD

**Issue by MicahZoltu** [NethermindEth/nethermind#2006]
`eth_getStorageAt` returns a 32-byte DATA in its response while Nethermind returns a hex encoded number as its response.  The difference is the presence of leading 0s so Geth will respond with:
```
0x000000000000000000000000395c60f1f54decc00f0f4f1e93727c5de81fb4cc
```
while Nethermind will respond with the following to the same request:
```
0x395c60f1f54decc00f0f4f1e93727c5de81fb4cc
```

**Comment by tkstanczak** [comment]
https://github.com/NethermindEth/nethermind/pull/2009

**Comment by MicahZoltu** [comment]
I believe this has been released?

**Comment by tkstanczak** [comment]
yes, the unit tests were updated and passing but we did not integration test it but I believe it should be fine now

**Comment by tjayrush** [comment]
I don't think this issue is fully closed.

If I run this curl command against both Parity and Geth

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getStorageAt","params":["0xf503017d7baf7fbc0fff7492b751025c6a78179a", "0x0", "0xa58ed0"],"id":1}'  <URL>
```
I get:

```
{"jsonrpc":"2.0","id":1,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"}
```

which is actually a bit of a weird result as the account does not actually exist.

Nethermind with the same command returns:

```
{"jsonrpc":"2.0","result":"0x","id":1}                                                                                                                                                                                                                                                                    
```
Nethermind version: `Nethermind/v1.8.90-0-67ccddc3b-20200913/X64-Linux/Core3.1.5` which is running at http://archivenode.io

It works as expected against both a real smart contract with known storage values and against EOA. In both cases the return values are 32-byte zero-left-padded.

**Comment by MicahZoltu** [comment]
@tjayrush You are saying that `0xf503017d7baf7fbc0fff7492b751025c6a78179a` is an account that has never signed any transactions and never had any transactions sent to it, and has never received any ETH?

If so, I can see the argument for either an error return *or* returning `0`.  All storage slots are assumed to default to `0`, and if the account doesn't exist (was never instantiated) it seems reasonable to return `0`.
