### ISSUE TITLE
Investigate Prysm interaction

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#2024]
![image](https://user-images.githubusercontent.com/498913/84445364-bfd9ee80-ac3b-11ea-8aae-01aa0cb081ee.png)

**Comment by nisdas** [comment]
Hey guys I tried running the latest release https://github.com/NethermindEth/nethermind/releases/tag/1.8.50 with Prysm in our testnet, unfortunately I still have some issues to do with unmarshalling `big Ints` in block bodies. 
Ex: 
```
ERROR powchain: could not query block with height 2881125: json: cannot unmarshal hex number with leading zero digits into Go struct field rpcBlock.transactions of type *hexutil.Big
```
We use go-ethereum's json-rpc client library to interface with all eth1 clients. Unmarshalling of responses fail here:
https://github.com/ethereum/go-ethereum/blob/a981b60c25e6be35ec37cf9b9625017c5fa67fdc/common/hexutil/json.go#L362 

The method `eth_getBlockByNumber` only fails whenever we request a specific block instead of the `latest`. Any ideas on how to proceed here ?

**Comment by tkstanczak** [comment]
Thanks for reporting this. It helps that you mentioned the client and the
method used. Big chance that we will be able to deploy it by tne end of day
today.

**Comment by MysticRyuujin** [comment]
I asked Butta over in the Prysm channel to test with `--jsonRpcConfig.BufferResponses true` (I assume that's the right CLI flag) and he said it didn't fix it.

@nisdas also said it didn't fix it.

**Comment by tkstanczak** [comment]
`EthModule` in `Nethermind.JsonRpc` contains series of methods to access block information. Prysm uses these methods to extract data about blocks. In particular we can assume that `eth_getBlockByHash` and `eth_getBlockByNumber` methods are used. Documentation of these methods can be found here: [JSON RPC Wiki](https://eth.wiki/json-rpc/API). Importantly the second parameter of these calls - a `bool` value - defines whether whole transaction objects are retrieved or only hashes. Based on Prysm reporting and after anlyzing their code I assume that the version with `true` value does not return properly formatted data. This should be compare with a synchronized `Goerli` Geth instance.

1) create a test curl method calling `eth_getBlockByNumber("[some block number for a block with transactions]", true)`
2) synchronize `Goerli` on Geth
3) synchronize `Goerli` on Nethermind
4) verify if the returned data is the same
5) if not the same then fix in Nethermind
6) if same then ensure that the data is same for all `Goerli` blocks
7) if the data is same for all `Goerli` blocks then launch Prysm against the Nethermind node and wait for the error and then issue the request for that particular block and check if it differs from a Geth version for this particular block and report back to Prysm if same (unlikely)
