### ISSUE TITLE
Ropsten sync issues / discussion

### ISSUE THREAD

**Issue by vindberg** [NethermindEth/nethermind#215]
Hi Tomasz,

im trying to run the Runner from within visual studio 2017. Im getting this error message:
_2018-11-06 09:41:48.7958|ERROR|1|Runner.Program|Failure|Config file does not exist configs\ropsten_windows_discovery.config.json_

Are the discovery files missing from the repo?

Thanks,
Anders.

**Comment by tkstanczak** [comment]
Hi Anders,

Thanks for reporting this. We changed the ropsten config file name to ropsten_windows.config.json (when running on windows) and ropsten_posix.config.son (when running on Mac or Linux). We have not updated VS project files references since we have all switched to Rider for development.

I will review the VS project files and write a Wiki where I will describe how to launch all the different testnets. This will be tracked in this issue and I will paste a link here.

Since it is on our priority list anyway I expect it to be available here by Friday, possibly tonight.
In the meantime you can change it in the project run config in VS.

A link for reference until we fix it:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/41b3ab99-ddc7-45d7-9196-86a3b2dc5516/how-to-pass-arguments-to-a-console-app-through-visual-studio-debugging-scenario?forum=csharpgeneral

**Comment by vindberg** [comment]
Thanks Tomasz, its running now on Ropsten:
2018-11-06 14:31:56.5617|INFO|4|Runner.Runners.JsonRpcRunner|Running server, url: http://127.0.0.1:8555|

I can't see it syncing the blockchain though? I can also wait for the wiki entry you mentioned .)

**Comment by tkstanczak** [comment]
It should go further, are you running on Windows?

Running server, url: http://127.0.0.1:8545|
Connected to 3 bootnodes, 4 trusted/persisted nodes|
Discovery App initialized.|
Starting http service, modules: Eth, Net, Web3, Db, Shh, Nethm, Debug|
Sync peers 1(1)/25 (sync in progress with [Peer|51c4b16b0b0f|0/4379523|Parity-Ethereum/v2.1.4-beta-bee2cb8-20181028/x86_64-linux-gnu/rustc1.30.0])|
JsonRPC initialization completed|
Processed blocks up to         1 in  14,192ms, mgasps    0.00 total    0.00, tps    0.00 total    0.00, bps    0.00 total    0.00, recv queue 0, proc queue 59|
Processed blocks up to       510 in   6,348ms, mgasps    0.20 total    0.06, tps    3.47 total    1.07, bps   80.18 total   24.78, recv queue 0, proc queue 0|
Sync peers 0(0)/25 (sync in progress with )|
Sync peers 1(1)/25 (sync in progress with [Peer|7697d7984511|510/4379525|Parity-Ethereum/v2.0.8-unstable-ef8f95e-20181015/x86_64-linux-gnu/rustc1.29.2])|
Processed blocks up to       511 in  21,604ms, mgasps    0.00 total    0.03, tps    0.00 total    0.52, bps    0.05 total   12.10, recv queue 1, proc queue 1|
Processed blocks up to      1020 in   1,537ms, mgasps    0.00 total    0.03, tps    0.00 total    0.50, bps  331.13 total   23.33, recv queue 0, proc queue 0|

**Comment by tkstanczak** [comment]
It may take a while before it finds first nodes to sync with (although for me it took under a minute)

**Comment by tkstanczak** [comment]
I will keep looking for some quality documentation format. Ropsten sync should run after you aunch it like here:
https://github.com/NethermindEth/nethermind/wiki/Ropsten-Sync

**Comment by tkstanczak** [comment]
This exception is thrown but handled and treated as non-critical and logged on the debug level. It suggests a compression algorithm / protocol mismatch between us and some nodes. Most likely these are some rogue nodes that are not following the rules properly and can be ignored since Parity and Geth communicate with us all fine.
Is my guess correct that the exception is shown in green in Visual Studio and not yellow? You can switch the settings in visual studio not to stop on user handled exception.

**Comment by tkstanczak** [comment]
For Ropsten hanging on Connected to 1 bootnodes
(1) it may take a while before finding the nodes to sync - did you wait with the app running for 5 / 10 minutes? (just in case there is some big struggle to find a valid node
(2) there is a log file in the [NethermindDIr]/logs which may contain any exception if they happened

**Comment by vindberg** [comment]
Interesting to know about the protocol mismatch from some nodes. Im hitting several different exceptions (User-Unhandled) regarding sync data.

For instance:
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Nethermind.Network
  StackTrace:
   at Nethermind.Network.Rlpx.NettyHandshakeHandler.ChannelActive(IChannelHandlerContext context) in ..Repos\nethermind\src\Nethermind\Nethermind.Network\Rlpx\NettyHandshakeHandler.cs:line 79
   at DotNetty.Transport.Channels.AbstractChannelHandlerContext.InvokeChannelActive()
```
Its the Channel object that is null:
`
            _p2PSession.RemoteHost = ((IPEndPoint)context.Channel.RemoteAddress).Address.ToString();`

However, the syncing is continuing which is good.

Thanks.

**Comment by tkstanczak** [comment]
@vindberg there are various different geth forks that people were running to support various ICO projects they were building - due to discovery protocol limitations often you cannot discard them before you start P2P conversation and there you may have protocol mismatch
Obviously it may be still an issue around how we handle snappy serialization and we plan to create a list of nodes that are causing this issue to occur and review whether these are in fact some random unfinished implementations / old buggy versions.

Object reference issue on channel is happening with a race conditions when two nodes are disconnecting but there are still messages being delivered. We would like to fix this but assigned to it lower priority since it happens when the nodes already decide to disconnect (this is or intuition so far). 

How is your sync progress on Ropsten?

**Comment by tkstanczak** [comment]
One of the three:
(1) you are running it on 32bit machine - Nethermind only runs on 64bit architectures
(2) some dependency is missing and you can track it by using this application on secp256k1.dll:
https://github.com/lucasg/Dependencies
(3) there is no secp256k1.dll in your Runner bin folder if VS failed to copy content properly (you can find it in the repo and copy to bin manually)

**Comment by vindberg** [comment]
One of two things worked:

1. I installed https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
2. I copied the secp256k1.dll from the External folder into the executing folder (and override the original dll)

Syncing now 👍

**Comment by vindberg** [comment]
Great.
Its at just about 110 GB in storage now, still running good. Is there any interface or dashboard of sorts for the node? Im sorry if I missed this feature in any documentation.

Best,
Anders

**Comment by tkstanczak** [comment]
Hi Anders,

If you are running the latest master then you can use JSON RPC (most of the methods supported by geth would work).

To make Nethermind run with JSON RPC you need to open the configuration file (configs/ropsten_windows.config.json) and set "JsonRpcEnabled": true and then set HttpHost and HttpPort. HttpHost - you can set it to 127.0.0.1 for local connections, internal or external IP depending on where you want to connect from. The node needs to be restarted after configuration changes.

You can look at the JSON RPC spec below - let us know if any methods that are missing would be important for you:
https://github.com/ethereum/wiki/wiki/JSON-RPC

Best,
Tomasz

**Comment by tkstanczak** [comment]
OK, I guess the list of peers would be missing now so we will need to cover that. 
I guess you will need:
 * net_peerCount
 * eth_syncing
 * net_istening

Track it in #227 and add any comments there. I guess this should be ready by the end of Monday

**Comment by tkstanczak** [comment]
http://validators-ropsten-1.westeurope.cloudapp.azure.com:8555/
will try to connect next time it is up
