### ISSUE TITLE
Extended reportBenign feature and corresponding fixes

### ISSUE THREAD

**Issue by varasev** [NethermindEth/nethermind#2393]
In POSDAO we will need to have an extended `reportBenign` function which would tell the `ValidatorSet` contract whether some validator skipped their block due to their offline/disconnected mode or just because of the previous validator (when the previous validator overlaps the block due to delay).

The idea is to add two extra parameters (`bool wasOnline, address parentBlockAuthor`) to the `reportBenign` function.

To make it possible, there are following steps suggested to be implemented in Nethermind:

`1.` Move the call of `ReportingContractBasedValidator.TryReportSkipped` from [`AuRaBlockProducer.SealBlock`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Consensus.AuRa/AuRaBlockProducer.cs#L131) to `AuRaBlockProducer.OnBlockSealed` (which would be called [here](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Blockchain/Producers/BlockProducerBase.cs#L124)).

This would guarantee that the `reportBenign` won't be sent by block's author until the block is sealed and suggested.

`2.` I think this is wrong (but I might mistake):

The `TryReportSkipped` is called by the [`AuRaSealValidator.ValidateParams`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs#L121) when block's non-author validates the block.

The `AuRaSealValidator.ValidateParams` is called by the [`HeaderValidator.Validate`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Blockchain/Validators/HeaderValidator.cs#L109-L114), but `HeaderValidator.Validate` is called by [`BlockValidator.ValidateHeader`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Blockchain/Validators/BlockValidator.cs#L50) which is only called by [`BlockDownloader.DownloadHeaders`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs#L201).

So, it seems that `TryReportSkipped` is called when the block is downloaded. But at that moment, as far as I understand, this block is not yet accepted by validators.

This will lead to a situation when we catch such a block which is not yet accepted, but already call `ReportBenign`. If previous validator `A` delayed their block (like on the picture below), but finally will produce it (earlier than block from `B` is accepted), the validator `A` will be reported as benign (which is not correct).

This point needs to be fixed so that validators should only send `ReportBenign` after the block is accepted by validators, not after it is downloaded. Because, as far as I understand, block's downloading doesn't mean that the block is already accepted.

<img src="https://user-images.githubusercontent.com/33550681/96569931-6f059100-12d2-11eb-846f-328f1da4b8e1.png" width="400" />

`3.` Probably, these two points above could be joined so that validators (including block's author) should only send `ReportBenign` after the block is accepted by them, not after it is downloaded or sealed by author.

`4.` [This `ReportBenign`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.cs#L110) implementation should be extended with the `bool wasOnline, address parentBlockAuthor` parameters (POSDAO ValidatorSet contract will have such a function correspondingly).

It is assumed that somehow we know (catch) whether the [`skippedValidator`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.cs#L195) tried to produce a block with the previous number ~and step~ (`header.Number - 1` ~and `header.AuRaStep.Value - 1`~), or not.

I.e. if the `skippedValidator` propagated their block `header.Number - 1` ~(with step `header.AuRaStep.Value - 1`)~ before we send `ReportBenign`, it means that the validator was online and thus the `wasOnline` parameter should be set to `true`. Otherwise, it should be `false`.

To make it possible we need to catch the propagated blocks in the client (and check them according to the described logic in the `TryReportSkipped/ReportBenign` function).

`5.` Other `ReportBenign` implementations (for [`IncorrectProposer` and `FutureBlock`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Consensus.AuRa/Validators/IReportingValidator.cs#L30-L31) reasons) should stay untouched (i.e. without the `bool wasOnline, address parentBlockAuthor` parameters). So, the corresponding `reportBenign` function in the `ValidatorSet` contract will have two versions (with those extra parameters and without them).

--

This will be a low priority task, but to be able to fix POSDAO contracts accordingly, currently I need to know if we can implement this.

Please, give your feedback.

**Comment by LukaszRozmej** [comment]
Points 1-3. I think you are right here and it would be beneficial to move Report skipped to after processing a block (both if it was produced by same node or other node). I would move it to:

https://github.com/NethermindEth/nethermind/blob/f2994f23dc967886c082866e20b32b093b806d1b/src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.cs#L226

4. This is very problematic and incompatible with AuRa. Consider this scenario:

![image](https://user-images.githubusercontent.com/12445221/96577565-1636f800-12d4-11eb-8f94-4c770b09346b.png)

AuRa basically has no means of punishing Validator who produced block in a slot after the slot it should have produced a block. Until someone produces a block on a block from Validator B, the block from Validator A will always win based on its TotalDifficulty and Difficulty as Difficulty will decrease with with time (AuraStep). Also we report before we receive that block from A.

What I would propose:
a) Create explicit ReportTime/ReportSlow (What about too fast?) to differentiate from Benign
b) Report basing on time received. If we receive block out of slot - report (only too slow? what about too fast?)
c) Seal another block in B time slot if possible
d) create new validator type to be used in chainspec (differentiate from 'contract' and 'safeContract')

**Comment by poaman** [comment]
@LukaszRozmej On your above picture (let's imagine that there is no `2B` block on the picture):

Would the block from `B` accepted in the current implementation?

It's based on the same parent as the block from `A`, but `B`'s propagated earlier. I think it will be accepted and the block from `A` will be rejected, right? Because when `B` is propagated, validators don't yet know about the block from `A`. I would expect that validators accept the block from `B` with `SkippedStep` benign report about `A`.

Is it right for the current implementation?

**Comment by poaman** [comment]
> Until someone produces a block on a block from Validator B, the block from Validator A will always win based on its TotalDifficulty and Difficulty as Difficulty will decrease with with time (AuraStep). Also we report before we receive that block from A.

@LukaszRozmej Do I get this correctly from your picture above, that validators will first accept the block from B, but once they a bit later receive the propagated block from A, it will be also accepted and will replace the block from B previously accepted because of Difficulty?

**Comment by LukaszRozmej** [comment]
@poaman yes this can be a scenario:

First accept Block B then Reorg to Block A as block A has higher difficulty and total difficulty. The exact scenario for each node will depend on propagation and discovery times for those blocks. If Node will accept Block B first then it will report benign.

**Comment by poaman** [comment]
@LukaszRozmej 

> If Node will accept Block B first then it will report benign.

It is OK if the validator `B` will report `SkippedStep` about validator `A` on your picture above (when the validator A actually finally produced the block). Such delays can be treated as offline, because so slowness should also be punished if it happens too often.

The main goal of the proposed changes is to let ValidatorSet contract know that validator `B` **tried** to produce block on his turn, and thus was online when he actually didn't produce (because his block was replaced with the block from the slow validator A (having higher difficulty) or because the block from `A` was propagated earlier than from `B` like on the [first picture](https://user-images.githubusercontent.com/33550681/96569931-6f059100-12d2-11eb-846f-328f1da4b8e1.png)).

> c) Seal another block in B time slot if possible

I don't like this approach because we don't know how much time will be taken by the block we repeatedly reproduce. We can take more time than we have before our slot elapses, so we can be reported as slow validator on the next block. There can also be other nuances I didn't think about yet.

Is it really impossible for a node to just remember the block it saw a bit earlier? Can't we keep it in memory after [`BlockDownloader.DownloadHeaders`](https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Synchronization/Blocks/BlockDownloader.cs#L201`, then check it inside the `TryReportSkipped`, and remove from the memory when it doesn't make sense to keep that anymore?

> Keep in mind that those reports will be based not only on Validator A behavior but also Network behavior. So if enough validators don't like Validator A and they will delay propagating its blocks he might get punished even when he is behaving correctly.

Yes, of course.

**Comment by LukaszRozmej** [comment]
Ah ok so the main problem we want to Solve is that when validator C produces block in slot 3 we don't want to report skipped B that was replaced with A? This sounds similar to uncles. This can be fairly easy achievable as BlockTree keeps branches. So if our Block 3 has parent block 1, we can check that it has uncle block 2 and not report it.

**Comment by poaman** [comment]
We do want to report about skipped `B` but with the `wasOnline` param as I described above because POSDAO contract needs to know how many times some validator skipped their turn unintentionally (i.e. being online) or intentionally (being offline).

We need this for both cases shown on the schemes below. Is that possible to use uncles for both cases?

(click to enlarge)

<img src="https://user-images.githubusercontent.com/33550681/96678881-438ab100-137b-11eb-9547-bbd5a180c447.png" width="300" /> <img src="https://user-images.githubusercontent.com/33550681/96678910-500f0980-137b-11eb-8048-f1e6f04ab9f9.png" width="300" />

If we'd use `uncles`, then the logic would be as follows:

**When we report benign, we first should check whether our block (which number we pass to the `reportBenign` function) has uncles: if it has uncles then we set `wasOnline` to `true` (when we report about the author of the uncle). Otherwise it must be `false`.**

Does Nethermind support working with uncles in AuRa? Or you mean we could implement a similar mechanism in Nethermind?

Blockscout explorer shows that there were no uncles on xDai, POA Core/Sokol at all: https://blockscout.com/poa/xdai/uncles, https://blockscout.com/poa/core/uncles, https://blockscout.com/poa/sokol/uncles

As far as I know, uncles is not the same as reorgs (so we need to be sure uncles are supported by the client): https://ethereum.stackexchange.com/questions/19646/difference-between-uncle-block-and-forked-blocks

**Comment by poaman** [comment]
> Points 1-3. I think you are right here and it would be beneficial to move Report skipped to after processing a block (both if it was produced by same node or other node). I would move it to: https://github.com/NethermindEth/nethermind/blob/f2994f23dc967886c082866e20b32b093b806d1b/src/Nethermind/Nethermind.Consensus.AuRa/Validators/ReportingContractBasedValidator.cs#L226

Seems a block producer first processes their block (before sealing): https://github.com/NethermindEth/nethermind/blob/a5db950b92aa976d47cce7f98aee1ed00d0a27fb/src/Nethermind/Nethermind.Blockchain/Producers/BlockProducerBase.cs#L108

Are you sure that is the right place to move `TryReportSkipped` to?

**Comment by LukaszRozmej** [comment]
@poaman so to be clear AuRa doesn't support uncles in a way that it doesn't add uncle information to produced blocks. But if the blocks get propagated they are in BlockTree on same level (blockNumber) as parent, so as an 'uncle', just used the term to be more familiar.

> We do want to report about skipped B but with the wasOnline param as I described above because POSDAO contract needs to know how many times some validator skipped their turn unintentionally (i.e. being online) or intentionally (being offline).
> When we report benign, we first should check whether our block (which number we pass to the reportBenign function) has uncles: if it has uncles then we set wasOnline to true (when we report about the author of the uncle). Otherwise it must be false.

Some comments and question marks here:
1. I would rename wasOnline to something more descriptive like - producedNonCanonicalBlock or wasReorganised  or something similar. wasOnline while short is confusing name.
2. Naming on the contract side, we want to have second reportBening function there? Maybe we should name it explicitly to reportSkipped?
3. When we are checking for 'uncles' before reporting we also have to check who sealed those uncles.
4. 
> Seems a block producer first processes their block (before sealing):

This is for validation purposes only. It processes the block on separate read-only view of chain and state. After sealing the block is propagated for normal processing on actual chain by adding it to BlockTree:

https://github.com/NethermindEth/nethermind/blob/eed064c478f53994c8590b5d2203479389ed92c3/src/Nethermind/Nethermind.Blockchain/Producers/BlockProducerBase.cs#L123

**Comment by poaman** [comment]
> if the blocks get propagated they are in BlockTree on same level (blockNumber) as parent, so as an 'uncle', just used the term to be more familiar

Ok, so in the current implementation such blocks are already in the BlockTree? (for the both cases I [mentioned above](https://github.com/NethermindEth/nethermind/issues/2393#issuecomment-713323909))

Or we will need to implement this functionality?

> I would rename wasOnline to something more descriptive like - producedNonCanonicalBlock or wasReorganised or something similar. wasOnline while short is confusing name.
> Naming on the contract side, we want to have second reportBening function there? Maybe we should name it explicitly to reportSkipped?

Ok, let's agree with the following name: `reportSkipped(address validator, uint256 blockNumber, bool reorganized, address parentBlockAuthor)`

> When we are checking for 'uncles' before reporting we also have to check who sealed those uncles.

Sure

**Comment by LukaszRozmej** [comment]
> Ok, so in the current implementation such blocks are already in the BlockTree? (for the both cases I mentioned above)

In general case it depends on propagation and network topology, but generally yes they should be in well connected network.

One idea that sprung to mind is that we can potentially use that 'uncle' information to report on slow validators. So if we process a block that reorganises other block with higher step we could assume that this block is late. This probably could be exploited by issuing a block with higher step too early. We do have some kind of validation about that here, but I think its too loose (and probably needs to be) to prevent that:

https://github.com/NethermindEth/nethermind/blob/c632039ff2b8997043b303e10ca2e325e0358d3c/src/Nethermind/Nethermind.Consensus.AuRa/AuRaSealValidator.cs#L101-L117

**Comment by poaman** [comment]
> One idea that sprung to mind is that we can potentially use that 'uncle' information to report on slow validators. So if we process a block that reorganises other block with higher step we could assume that this block is late.

For such cases there will be `address parentBlockAuthor` parameter in the `ValidatorSetAuRa.reportSkipped` function as I mentioned above. If `bool reorganized` param is `true`, then it would mean that the validator `parentBlockAuthor` who produced the previous block (`blockNumber - 1`) delayed that block. So I think we don't need any other reports on slow validators.

**Comment by varasev** [comment]
We decided to implement another scheme which won't require modifications in Ethereum client, so I'm closing this issue.
