### ISSUE TITLE
admin_peers found but the containing module is disabled, consider adding module to JsonRpcConfig.EnabledModules

### ISSUE THREAD

**Issue by xuanyuan219** [NethermindEth/nethermind#3194]
[]  2021-07-05 15:54:49.5133|Error when handling ID 3, admin_peers() | {"jsonrpc":"2.0","error":{"code":-32600,"message":"admin_peers found but the containing module is disabled, consider adding module to JsonRpcConfig.EnabledModules"},"id":3} 

I run xdai network, prompt the above error, how to solve？

**Comment by kdonthi** [comment]
In the `Nethermind.Runner/configs/xdai.cfg` file, under JsonRpc, add an EnabledModules field so that the JsonRpc section looks like this:

"JsonRpc": {
  "Enabled": false,
  "Timeout": 20000,
  "Host": "127.0.0.1",
  "Port": 8545,
  "WebSocketsPort": 8546,
  "EnabledModules": ["Admin", "Eth", "Subscribe", "Trace", "TxPool", "Web3", "Personal", "Proof", "Net", "Parity", "Health"]
},
