### ISSUE TITLE
[1.12.1] [Archive] Debug.TraceBlockByNumber Always Fails

### ISSUE THREAD

**Issue by Texnomic** [NethermindEth/nethermind#3668]
Calling RPC Method `Debug.TraceBlockByNumber` Always Fails with `Internal error: debug_traceBlockByNumber`

Note: Most times it never returns even with 2 minute timeout.

**Comment by tkstanczak** [comment]
Thanks @Texnomic , we will investigate soon. Assigned to @kjazgar

**Comment by LukaszRozmej** [comment]
Internal error should have an exception trace in the message or logs, can you send that over?

**Comment by Texnomic** [comment]
@LukaszRozmej this error is coming through Web3 RPC. I'm using `Nethereum` btw.

**Comment by LukaszRozmej** [comment]
@Texnomic we need message from Nethermind logs about this failure with details about exception

**Comment by LukaszRozmej** [comment]
Geth like style traces on mainnet can be very, very big. Like few GB's of data. To push that through HTTP, you need a lot of time. I was able to successfully  trace smaller blocks on our archive node like 13808604 or 13808601 under 20 s timeout.

In order to trace a very heavy block you probably don't want to do that through http and we need to implement something like geth's: https://geth.ethereum.org/docs/rpc/ns-debug#debug_standardtraceblocktofile

**Comment by LukaszRozmej** [comment]
We already have this as a TODO item, so I will bump it higher: https://github.com/NethermindEth/nethermind/issues/2263

**Comment by Texnomic** [comment]
@LukaszRozmej All right, thank you
