### ISSUE TITLE
[SnapSync] Pivot changes to often

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4551]
For some reason Pivot changes very often with very small jumps during the Ranges phase.
In the beginning the jumps are ok (should be bigger but are acceptable) but later during the Ranges phase the jumps are very often and usually just by one block.
It doesn't break anything but probably slows down the Ranges phase and maybe healing (more holes).
It only happens on my slower VM and causes more than 200 pivot changes in Ranges phase.
The faster VM works ok - just around 5 pivot changes. 

`SNAP - to many empty responses - Pivot changed from 15479802 to 15479803`

[mainnet.logs.txt](https://github.com/NethermindEth/nethermind/files/9538862/mainnet.logs.txt)

**Comment by asdacap** [comment]
This seems likely due to:
- Lack of throttling on response byte which tend to cause a lot of timeouts. Fixed by https://github.com/NethermindEth/nethermind/pull/4528 (not in develop)
- Combined with this logic, which seems to mean, if you have a lot of consecutive failures (probably because of previous issue), pivot get reset. https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Synchronization/SnapSync/SnapSyncFeed.cs#L179
- Probably also due to lack of throttling on creating request, which increase the number of request. I'll make a PR for this... it makes download faster in any case.

**Comment by asdacap** [comment]
Not sure what changed, but definitely does not happen anymore.
