### ISSUE TITLE
Coding standard

### ISSUE THREAD

**Issue by dceleda** [NethermindEth/nethermind#4582]
Align coding standards across PRs.
Create a linter that automatically formats everyone's code to the same code style. For example, Warp uses this for TypeScript: https://github.com/NethermindEth/warp/blob/develop/.eslintrc.json. 
They also have what’s a called a ‘pre-commit hook’ which means every time we ‘git commit’ it automatically formats their code to some agreed code formatting.

**Comment by dceleda** [comment]
Please create a notion page first with suggestions that the team should agree to.

**Comment by dceleda** [comment]
I'm not sure if we need any strict rules. Let's what the team thinks.
One thing that we need for sure is whitespace automatic formatting in IDEs to avoid situation when we have so many changes whoever touches a file.

**Comment by smartprogrammer93** [comment]
We have https://github.com/NethermindEth/nethermind/blob/master/.editorconfig
I am not sure if VS is respecting it since it is outside of the folder of the solution
but we can call dotnet format
https://github.com/dotnet/format
pre commit using hooks. but that will require everyone to install dotnet format.
it is the simplest solution i found

**Comment by smartprogrammer93** [comment]
With the suggested approach above, users need to : 
1. install dotnet format
```
dotnet tool install -g dotnet-format
``` 
2. assign the hooksPath like so
```
git config --local core.hooksPath .githooks/
```
