### ISSUE TITLE
Any plan to support AuRa?

### ISSUE THREAD

**Issue by jzarifis** [NethermindEth/nethermind#478]
I have tried with kovan network and received
Error during ethereum runner start|System.NotSupportedException: Seal engine type AuRa is not supported in Nethermind

**Comment by tkstanczak** [comment]
I have asked Afri about it and Kovan has multiple modifications that are Parity specific (e.g. its own flavour of eWASM). Above that, Parity dropped support for Kovan in their announcement - https://www.parity.io/announcing-the-end-of-parity-support-for-kovan/.

So, since Parity was the only client supporting Kovan it should be considered a deprecated testnet.

We have discussed support for AuRa for POA Core but this is currently not funded.

**Comment by jzarifis** [comment]
Thanks for your response, the AuRa is the interesting stuff not the Kovan itself

**Comment by tkstanczak** [comment]
AuRa will be supported

**Comment by tkstanczak** [comment]
work in progress
