### ISSUE TITLE
Gas estimations on Gnosis Chain too low 

### ISSUE THREAD

**Issue by iamacook** [NethermindEth/nethermind#5637]
**Description**

`eth_estimateGas` estimations on Gnosis Chain are too low (specifically for Safe transactions requiring [`safeTxGas`](https://help.safe.global/en/articles/4738445-advanced-transaction-parameters)).

**Steps to Reproduce**

Make `eth_estimateGas` calls to either of the official Gnosis Chain RPCs: `https://rpc.gnosischain.com` / `https://rpc.gnosis.gateway.fm` and observe the low gas which inevitably reverts ([simulation](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/f12a8f97-5bb9-432e-b1dd-be21398fe61a)):

```json
{
    "method": "eth_estimateGas",
    "params": [
        {
            "type": "0x0",
            "from": "0xbbeedb6d8e56e23f5812e59d1b6602f15957271f",
            "to": "0x828cf988de33bf93527533852e95e2da449ec171",
            "data": "0x6a761202000000000000000000000000828cf988de33bf93527533852e95e2da449ec171000000000000000000000000000000000000000000000000000000e8d4a51000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014bb80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041e0a9f565f27a4fd5743e5b7ad92f4217467bc5a7a419c7e159a5950de845ad9b0e88bf1c5549d5335ca087c010a7560a5caf991ba88850d10cb1e2d6196b4a151b00000000000000000000000000000000000000000000000000000000000000"
        }
    ],
    "id": 63,
    "jsonrpc": "2.0"
}
```

**Actual behavior**

Estimation is too low and transaction reverts.

**Expected behavior**

Estimation returns sufficient gas for the transaction to succeed, ~30-60% higher than what it currently is.

**Comment by emlautarom1** [comment]
I'm able to reproduce the issue on 43660b6a730730b9cd561f116cf546660fabe6da using the following JS script that leverages `ethers`:

```javascript
const ethers = require("ethers");

(async () => {
    [
        { client: "Localhost", url: "http://127.0.0.1:8545/" },
    ].forEach(async ({ client, url }) => await estimateGas(client, url));
})();

async function estimateGas(client, url) {
    let body = {
        "from": "0xbbeedb6d8e56e23f5812e59d1b6602f15957271f",
        "to": "0x828cf988de33bf93527533852e95e2da449ec171",
        "data": "0x6a761202000000000000000000000000828cf988de33bf93527533852e95e2da449ec171000000000000000000000000000000000000000000000000000000e8d4a51000000000000000000000000000000000000000000000000000000000000000014000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014bb80000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041e0a9f565f27a4fd5743e5b7ad92f4217467bc5a7a419c7e159a5950de845ad9b0e88bf1c5549d5335ca087c010a7560a5caf991ba88850d10cb1e2d6196b4a151b00000000000000000000000000000000000000000000000000000000000000"
    }

    let response = await ethers.utils.fetchJson(url, `{ "id": 42, "jsonrpc": "2.0", "method": "eth_estimateGas", "params": [${JSON.stringify(body)} ] }`);
    let estimation = parseInt(response.result, 16);
    console.log(`Client '${client}' estimated '${estimation}'`);
}

```

**Comment by emlautarom1** [comment]
After verifying with a simulator, the actual gas used to execute this transaction is `56285` (see https://dashboard.tenderly.co/shared/simulation/df8e2e37-9336-447b-9d13-bd5359bd3129). Still, the transaction requires a higher gas limit due to the existence of `safeTxGas` (documented here: https://help.safe.global/en/articles/40837-advanced-transaction-parameters). The contract involved in the transaction will check that the remaining gas is at least the value of `safeTxGas`, which, in this case, is `84920` since that is the value that the user has provided..

If we run the transaction again with the estimation provided by the RPCs + the value of `safeTxGas` (`59074 + 84920 = 143994`), then the transaction actually goes through.

How should then Nethermind deal with this kind of transactions that can perform arbitrary checks on the gas? For this specific kind of "safe" transactions, a possibility would for Nethermind to have a special condition (a plugin?) to add the value of `safeTxGas` to the original estimation. What do you think @deffrian?
