### ISSUE TITLE
Create page about validatior performance <> attestations

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/nethermind#5763]
example - describe attestations during old bodies/full pruning
What metrics are important
Mention about importance of fast SSD, ideally NVMe

**Comment by OlegJakushkin** [comment]
Autogenerated draft. To be updated with:
 - Real metrics values
 - Graphs examples

# Validator Performance and Attestations in Nethermind Ethereum Blockchain Client

In the Nethermind Ethereum Blockchain client, validator performance and attestations are critical aspects to consider for optimal operation and maintenance. They play a significant role in the correct functioning and efficient performance of the Ethereum network.

## Validator Performance
Validator performance in the Nethermind Ethereum client is critical for the operation of the Ethereum blockchain, as it refers to the efficiency and effectiveness of a validator node in verifying and proposing new blocks. It involves several factors, including computational power, network speed, and storage capacity.

The key metrics to evaluate validator performance include:

1. **Block Proposals**: The number of blocks proposed by the validator.

2. **Attestations**: The number of attestations made by the validator.

3. **Slashings**: The number of times the validator has been slashed for malicious behavior.

4. **Inclusion Distance**: The number of slots between when a validator’s attestation should have been included and when it was actually included.

5. **Uptime**: The ratio of the total number of times a validator is online and available to validate transactions to the total time.

## Attestations
Attestations in the Ethereum network refer to the votes by validators concerning the validity of a block. In other words, when a validator observes that a block has been processed correctly, it attests to that block.

The two types of pruning in Nethermind are old bodies and full pruning. 

**Old bodies pruning** - In this mode, the state is fully kept and only old block bodies are pruned. Attestations during this type of pruning are important as validators need to check the validity of recent blocks. 

**Full pruning** - In full pruning, the entire data older than a certain point is removed, including the state and the block bodies. Attestations become crucial in this scenario because validators need to make sure the blocks they're validating aren't pruned.

## Importance of SSD, Ideally NVMe

The performance of a validator in the Nethermind Ethereum client is significantly impacted by the type of storage used. Fast Solid State Drives (SSD), and particularly NVMe (Non-Volatile Memory express) drives, are recommended.

NVMe drives provide several advantages:

1. **Speed**: NVMe drives are faster than traditional SSDs, which leads to quicker block validation and attestation.

2. **Concurrency**: NVMe drives can handle more simultaneous connections, allowing for more efficient processing of multiple transactions and blocks.

3. **Efficiency**: NVMe drives use less power per transaction, making them more energy-efficient.

4. **Durability**: NVMe drives tend to have a longer lifespan than traditional SSDs, leading to less downtime for maintenance and replacements.

For these reasons, utilizing an NVMe drive can greatly enhance the validator performance in the Nethermind Ethereum client.

**Comment by OlegJakushkin** [comment]
# Missing Attestations
Ethereum network attestations are validator votes on block validity. A validator's performance is pivotal to the Ethereum blockchain's operation, gauging a node's efficiency in verifying and proposing blocks.

## FAQ

**Q: Often, I am missing my attestations, why?**  
**A**: Check the type of Drive you are using, it should be an NVMe SSD. Perhaps you're not fully synced? Also, check your networking performance - you might be losing connection intermittently. Don't hesitate to share your problems on our Discord channel.

**Q: Do you know how it is related to full pruning and old bodies/receipts sync?**  
**A**: If pruning (**Old Bodies Pruning** or **Full Pruning**) is in progress, it can affect Attestations performance. Please refer to the related metrics.

**Q: What metric in Nethermind is related to it?**  
**A**: Please refer to the following metrics: `nethermind_new_payload_execution_time`, `nethermind_state_db_pruning`. If you see times exceeding 2 seconds, it could indicate a problem.

![nethermind_new_payload_execution_time in Grafana](https://github.com/NethermindEth/nethermind/assets/2915361/d708ca8a-4573-4e02-8c57-b0cb8120117c.png)

**Comment by OlegJakushkin** [comment]
Done. See here for [final reference](https://docs.nethermind.io/nethermind/nodes-and-the-merge/troubleshooting-issues/missing-attestations)
