### ISSUE TITLE
Block Processing right after OldReceipts is not working for a few minutes (not always reproducible)

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#6629]
**Steps to Reproduce**
1. Sync gnosis or mainnet eth node until OldReceipts
2. Wait for OldReceipts to complete
3. Observe logs

**Actual behavior**
For some reason (in this case Gnosis chain) right after OldReceipts completed BlockProcessing stops working which was not a case in previous versions. Below is a snippet of logs from Seq
[export-8dc20a6d5dbceae.csv](https://github.com/NethermindEth/nethermind/files/14081935/export-8dc20a6d5dbceae.csv)

**Expected behavior**
Block Processing as it works in parallel with OldReceipts should not be interupted when sync of Receipts is completed.

**Comment by asdacap** [comment]
I'm guessing that after old receipt complete, it will tune to old configuration and will immediately stall due to very high l0 file number. `options.SetLevel0StopWritesTrigger(20000);` would prevent it from stalling but not slowing down. Still need to reproduce and confirm this. However, it runs the risk of causing the l0 file number to allocate which slows it down until it is processed.

**Comment by asdacap** [comment]
`2024/01/30-08:29:20.718205 81014 [WARN] [db/column_family.cc:988] [Blocks] Stalling writes because we have 476 level-0 files rate 1533708`

**Comment by asdacap** [comment]
`2024/01/30-08:34:43.552114 126881 [WARN] [db/column_family.cc:945] [Blocks] Stopping writes because we have 115 level-0 files`

**Comment by asdacap** [comment]
Heavy write l0 file is 256. So.. this sounds about right.

**Comment by asdacap** [comment]
Need to throttle to have at least one block hanging. ` --Db.ReceiptsDbMaxBytesPerSec 50000000`
