### ISSUE TITLE
Support initiate / finalize change on AuRa

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#663]

**Comment by raymondjacobson** [comment]
Hi @LukaszRozmej , @tkstanczak , I'm running a fork of an AuRa/POA implementation, and it appears as if finalizeChange never gets called for validators in the pendingList. I'm not sure why they aren't, but I'm wondering if this is potentially a nethermind bug (?).

IIUC, by https://blockchain101.com/wp-content/uploads/2021/08/TheDeFi20.pdf, it suggests that any time a validator change is triggered and initiate change event is fired, it should be finalized, and I'm not observing that to be the case.

Do you have any suggestions?

**Comment by LukaszRozmej** [comment]
Hi @raymondjacobson this feature is successfully deployed on multiple chains: Gnosis (former xDai), Sokol, Poa Core, EWC, Volta ect. where everywhere it works fine and is with consensus with OpenEthereum implementation.

 The confusion is probably when finalizeChange is being called. So finalizeChange is being called when block where initiateChange was emitted is finalized. So when this happens? It happens when enough current (before the change) validators build a block on-top of the block that emitted initiateChange. How many is dependent on twoThirdsMajorityTransition flag in chainspec. If that flag is false it needs to be  > 1/2, if its true it needs to be > 2/3.

Let me give you an example. Lets say we have a network where we have 5 validators: A, B, C, D, E and twoThirdsMajorityTransition flag is true. so we need > 2/3*5 = 3 1/3,  so we need 4 confirmations to mark block as finalized.

Validator A builds block 1 which contains initiateChange. We have 1 confirmation of this block from validiator A.
Validator B builds block 2 on top of that block. So we have 2 confirmations.
Validator C builds block 3 on top of that block. So we have 3 confirmations.
Validator D builds block 4 on top of that block. So we have 4 confirmations. This is enough confirmations to finalize block 1, so when processing block 4 nodes call finalizeChange method.

Similarly in this example if we have 2 out of 5 validators offline not building blocks then finalization will never happen and finalizeChange will never be called. Example:

Validator A builds block 1 which contains initiateChange. We have 1 confirmation of this block from validiator A.
Validator B builds block 2 on top of that block. So we have 2 confirmations.
Validator C builds block 3 on top of that block. So we have 3 confirmations.
Validator D is offline and skips building a block. We still have only 3 confirmations.
Validator E is offline and skips building a block. We still have only 3 confirmations.
Validator B builds block 4 on top of that block. But we still have only 3 validator confirmations.
...

**Comment by raymondjacobson** [comment]
Thanks @LukaszRozmej  -- This was weird. I sort-of figured out what was going on in this situation, but essentially I performed a hard-fork from a validator set that was entirely on OpenEthereum via a change to an AuRa contract to a new set of validators entirely on Nethermind. Here's what happened:

1. Created a new consensus contract and deployed it to the main chain (all open ethereum validators) with a "master of ceremony" initial validator.
2. Registered 3 more validators against that new main chain in the consensus contract (all nethermind)
3. Updated the chain spec in all 4 validators (master + 3 additional) to include a target block in the future with activation of the consensus contract
4. On hitting the target block, the validators were all in the PendingList *not* the Validators list except for the master of ceremony (initial validator), which was in the validators list.
5. The single master of ceremony was mining blocks
6. 100s of blocks later, the 3 additional validators were still stuck in the pending state
7. I add a 4th additional validator and registered it against the *new* fork
8. That forced all 4 additional validators from the pending list to the validators list

I'm not sure if this is a bug, but it seems like something between the openethereum <> nethermind handshake broke the state tracking.

**Comment by LukaszRozmej** [comment]
Ah interesting. That's quite an edge case to make a completely different validator list. That would have to be investigated further.

**Comment by LukaszRozmej** [comment]
As a current workaround my suggestion would be to split the upgrade into 2 stages:
1. New contract but same validators. Let it validate some blocks.
2. Initiate change in contract to switch to Nethermind nodes.

Should work without issues.
