### ISSUE TITLE
[Holesky] After syncing node with Lodestar, seems like we returning opposite values to FCU and newPayload

### ISSUE THREAD

**Issue by kamilchodola** [NethermindEth/nethermind#7117]
After Sync of holesky I noticed that blocks are not being processed properly and we are receiving blocks which should be already processed:
30 May 2024 14:53:17.326 Processed     **1639536...  1639537**
30 May 2024 14:54:16.471 Valid... A new payload ignored. Block **1639384** (0x8b69ee...eed8b0) found in main chain.

Also for FCU calls we are responding as Syncing: 
30 May 2024 15:09:57.826 Syncing beacon headers, Request: ForkChoice: 1639432 (0x9d97cd...c98eb9), Safe: 1639383 (0xc33b8d...635442), Finalized: 1639383 (0xc33b8d...635442)

Node is not able to sync to the head and stuck on some old blocks.

This happens only on Holesky chain - none other is having such problem. It is only reproducible with Lodestar.

**Comment by estherbreath** [comment]
I am a blockchain developer in Solidity and Cairo, as well as a backend developer.
I ask to be assigned this issue please, with a promise to deliver accurately and in good time.

To solve this issue, the first thing I would use the node health monitoring tools provided by Nethermind to check for errors, ensuring the configuration matches the expected parameters.

Increase the logging level in Nethermind to get more detailed information about what's happening during the sync process, taking note of errors or warnings that occur around the time blocks are received. Taking into consideration where the error occurs on both testnets and the mainnet.

Lastly, re-syncing the chain.

**Comment by MarekM25** [comment]
This problem happens when:
-state sync synced to block X
-CL sends newPayload to block X-Y and gets VALID because of this condition: https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/NewPayloadHandler.cs#L150
-For the same block, CL sends FCU and gets SYNCING because of this condition (WasProcessed is false before stateSync?): https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Merge.Plugin/Handlers/ForkchoiceUpdatedHandler.cs#L185

So, for newPayload we responded VALID correctly, and for FCU for the same block we responded SYNCING. I think this very likely confuses the CL client. We should return VALID for both
