### ISSUE TITLE
Fix GitVersion

### ISSUE THREAD

**Issue by tkstanczak** [NethermindEth/nethermind#969]
btw, currently nethermind uses a non standard version identifier in the clientId: nethermind/v1.1.8-/x64-linux 4.15.0-66-generic/core3.0.0 (v1.1.8- is not a valid semver identifer) any chance to update it to a version string that is similar to the other clients on the network (v2.6.4-beta-badb04502f-20190926 for example)

**Comment by sgryphon** [comment]
SemVer specs are here: https://semver.org/

However the example "v2.6.4-beta-badb04502f-20190926" isn't really SemVer either. SemVer does not have a leading "v", and the hex and date look more like build metadata than part of the version.

Maybe "2.6.4-beta+badb04502f-20190926", although "2.6.4-beta.1+badb04502f.20190926" might be more common (parts are separate by dots, so the later has two build metadata parts -- the SHA and date -- rather than one part containing a mix of both).

An easy way to automatically generate SemVer values is GitVersion, https://github.com/GitTools/GitVersion

It can work out which branch you are on and generate the appropriate version / pre-release, based on merges and other data.

I have an example of using it in my local build scripts for cortex (build.ps1).

**Comment by tkstanczak** [comment]
@matilote leaving that with you for Monday

**Comment by tkstanczak** [comment]
or whenever you prioritize it

**Comment by sgryphon** [comment]
Improving the tool usage in Eth 2.0 so that I didn't have to check in the tool binaries, I found the msbuild task works really nicely and pretty much automatic, so are doing a pull request that will basically solve this issue.
